# --- Database Settings ---
# Pydantic's discriminated union loader expects all keys
# for the selected 'type' to be flat inside this section.
[database]
type = "sqlite3"
db_location = "db.sqlite3"
in_memory = false

# type = "mssql"
# server_name = "RSSC30-DB0140"
# db_name = "AnalyticsDataMart"
# driver = "ODBC Driver 17 for SQL Server"
# trusted_connection = "yes"
# schema_name = "e2ude_core_dev"

# --- Logging Settings ---
[logging]
level = "DEBUG"
log_to_file = true
log_file = "main.log"
rotation_size_mb = 10
rotation_backup_count = 5
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
