[paths]
scan_root = "\\\\Rsiny1-ilsfs\\RSM"

[runtime]
discovery_mode = "incremental"
discovery_workers = 1024
pipeline_buffer_size = 60
unzip_workers = 60
process_workers = 8

[diagnostics]
enable_viztracer = false
